apiVersion: apps/v1
kind: Deployment
metadata:
  name: pome-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pome-back
  template:
    metadata:
      labels:
        app: pome-back
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: pome-back
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          name: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: pome-back
spec:
  ports:
  - port: 6379
  selector:
    app: pome-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomee-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pome-front
  template:
    metadata:
      labels:
        app: pome-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: pome-front
        image: microsoft/pome-front:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: MONGO
          value: "pome-back"
---
apiVersion: v1
kind: Service
metadata:
  name: pome-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: pome-front